name: maplibre_gl
publish_to: 'none'
repository: https://github.com/tetrochel/flutter-maplibre-gl

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dev_dependencies:
  melos: ^6.0.0
  very_good_analysis: ">=5.0.0 <7.0.0"
