name: maplibre_gl_platform_interface
publish_to: none
description: A common platform interface for the maplibre_gl plugin. This package is only intended to be used by the maplibre_gl package.
repository: https://github.com/tetrochel/flutter-maplibre-gl

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.5

dev_dependencies:
  very_good_analysis: ^5.0.0
